CREATE SCHEMA IF NOT EXISTS DESAFIO_FORTES;

USE DESAFIO_FORTES;

CREATE TABLE IF NOT EXISTS CLIENTES(
ID_CLIENTE INT primary KEY NOT NULL,
NOME_CLIENTE VARCHAR(45) NOT NULL,
UF CHAR (2) NOT NULL,
CPF_CLIENTE VARCHAR (20) NOT NULL,
RUA VARCHAR (100) NOT NULL,
BAIRRO VARCHAR (100) NOT NULL,
TELEFONE VARCHAR (20) NOT NULL,
EMAIL VARCHAR (50) NOT NULL
);

CREATE TABLE IF NOT EXISTS LOCALIZAÇÕES(
ID_LOCALIZAÇÃO INT NOT NULL PRIMARY KEY,
CIDADE VARCHAR (100) NOT NULL,
ESTADO VARCHAR (100) NOT NULL,
PAIS VARCHAR (100) NOT NULL,
BAIRRO VARCHAR (45) NOT NULL
);

CREATE TABLE IF NOT EXISTS SUBEMPREITEIROS(
ID_SUBEMPRETEIRO INT NOT NULL PRIMARY KEY,
NOME VARCHAR (100) NOT NULL,
CONTATO VARCHAR (45) NOT NULL,
TELEFONE VARCHAR (20) NOT NULL
);

CREATE TABLE IF NOT EXISTS QUALIFICAÇÕES(
ID_QUALIFICAÇÃO INT NOT NULL PRIMARY KEY,
DESCRICAO TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS DEPARTAMENTOS(
ID_DEPARTAMENTO INT NOT NULL PRIMARY KEY,
NOME_DEP VARCHAR (100) NOT NULL
);

CREATE TABLE IF NOT EXISTS FORNECEDORES(
ID_FORNECEDOR INT NOT NULL PRIMARY KEY,
NOME_FORNEC VARCHAR (100) NOT NULL,
CNPJ VARCHAR (20) NOT null,
CIDADE VARCHAR (100) NOT NULL
);

CREATE TABLE IF NOT EXISTS INSTITUICOES_CARENTES(
ID_INSTITUICAO_CARENTE INT NOT NULL primary KEY,
NOME_INST VARCHAR (100) NOT NULL,
CNPJ VARCHAR (20) NOT NULL,
CIDADE VARCHAR (100) NOT NULL,
BAIRRO VARCHAR (100) NOT NULL,
TELEFONE VARCHAR (20) NOT NULL
);

CREATE TABLE IF NOT EXISTS PROJETOS_FORTES(
ID_PROJETO_FORTES INT primary KEY NOT NULL,
NOME_PROJETO VARCHAR (100) NOT NULL,
DATA_INICIO DATE NOT NULL,
DATA_TERMINO DATE NOT NULL,
ID_CLIENTE INT NOT NULL,
ID_LOCALIZACAO INT NOT NULL,
CONSTRAINT PROJETOS_CLIENTES FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE),
constraint LOCALIZACAO_PROJETOS FOREIGN KEY (ID_LOCALIZACAO) REFERENCES LOCALIZAÇÕES (ID_LOCALIZAÇÃO)
);

CREATE TABLE IF NOT EXISTS PROJETOS_SOCIAIS(
ID_PROJETO_SOCIAL INT primary KEY NOT NULL,
NOME VARCHAR (100) NOT NULL,
DATA_INICIO DATE NOT NULL,
DATA_TERMINO DATE NOT NULL,
ID_PROJETO_FORTES INT NOT NULL,
CONSTRAINT PROJETOS FOREIGN KEY (ID_PROJETO_FORTES) REFERENCES PROJETOS_FORTES(ID_PROJETO_FORTES)
);

CREATE TABLE IF NOT EXISTS EQUIPAMENTOS(
ID_EQUIPAMENTO INT NOT NULL primary KEY,
NOME_EQUIP VARCHAR (100) NOT NULL,
TIPO_EQUIP VARCHAR (100) NOT NULL,
ID_FORNECEDOR INT NOT NULL,
constraint FORNECED_EQUIP FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDORES (ID_FORNECEDOR)
);

CREATE TABLE IF NOT EXISTS MATERIAIS(
ID_MATERIAL INT NOT NULL PRIMARY KEY,
DESCRICAO_MAT TEXT NOT NULL,
PRECO_MAT DECIMAL (10,2) NOT NULL,
ID_FORNECEDOR INT NOT NULL,
constraint FORNEC_MAT FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDORES (ID_FORNECEDOR)
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS(
ID_FUNCIONARIO INT NOT NULL PRIMARY KEY,
NOME_FUNCIONARIO VARCHAR (50) NOT NULL,
CARGO_FUNCIONARIO VARCHAR (45) NOT NULL,
ID_SUPERVISOR INT NOT NULL,
ID_DEPARTAMENTO INT NOT NULL,
constraint SUPERVISOR_FUNCIONARIO FOREIGN KEY (ID_SUPERVISOR) REFERENCES FUNCIONARIOS (ID_FUNCIONARIO),
CONSTRAINT DEPARTAM_FUNCION FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTOS (ID_DEPARTAMENTO)
);

CREATE TABLE IF NOT EXISTS SUBEMPREITEIROS_FORTES(
ID_SUBEMPREITEIRO INT NOT NULL,
ID_PROJETO_FORTES INT NOT NULL,
primary key (ID_SUBEMPREITEIRO, ID_PROJETO_FORTES),
CONSTRAINT PROJ_SUBEMPR FOREIGN KEY (ID_SUBEMPREITEIRO) REFERENCES SUBEMPREITEIROS (ID_SUBEMPRETEIRO),
constraint FORTES_SUBEMPR FOREIGN KEY (ID_PROJETO_FORTES) REFERENCES PROJETOS_FORTES (ID_PROJETO_FORTES)
);

CREATE TABLE IF NOT EXISTS EQUIPAMENTOS_PROJETOS(
ID_EQUIP INT NOT NULL,
ID_PROJ INT NOT NULL,
primary key (ID_EQUIP, ID_PROJ),
CONSTRAINT EQUIP_PROJ FOREIGN KEY (ID_EQUIP) REFERENCES EQUIPAMENTOS (ID_EQUIPAMENTO),
CONSTRAINT PROJ_EQUIP FOREIGN KEY (ID_PROJ) REFERENCES PROJETOS_FORTES (ID_PROJETO_FORTES)
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS_PROJETOS(
ID_PROJ INT NOT NULL,
ID_FUNCIO INT NOT NULL,
primary key (ID_PROJ, ID_FUNCIO),
CONSTRAINT PROJ_FUNCIO FOREIGN KEY (ID_PROJ) REFERENCES PROJETOS_FORTES (ID_PROJETO_FORTES),
CONSTRAINT FUNCION_PROJ FOREIGN KEY (ID_FUNCIO) REFERENCES FUNCIONARIOS (ID_FUNCIONARIO)
);

CREATE TABLE IF NOT EXISTS FORNECEDORES_SUBEMPREITEIROS(
ID_FORNECEDOR INT NOT NULL,
ID_SUBEMPR INT NOT NULL,
primary key (ID_FORNECEDOR, ID_SUBEMPR),
CONSTRAINT FORNEC_SUBEMPR FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDORES (ID_FORNECEDOR),
CONSTRAINT SUBEMPR_FORNEC FOREIGN KEY (ID_SUBEMPR) REFERENCES SUBEMPREITEIROS (ID_SUBEMPRETEIRO)
);

CREATE TABLE IF NOT EXISTS MATERIAIS_PROJETOS_FORTES(
ID_PROJ_FORTES INT NOT NULL,
ID_MAT INT NOT NULL,
primary key (ID_PROJ_FORTES, ID_MAT),
CONSTRAINT PROJ_MAT FOREIGN KEY (ID_PROJ_FORTES) references PROJETOS_FORTES (ID_PROJETO_FORTES),
CONSTRAINT MAT_PROJ FOREIGN KEY (ID_MAT) REFERENCES MATERIAIS (ID_MATERIAL)
);

CREATE TABLE IF NOT EXISTS QUALIFICACOES_FUNCIONARIOS(
ID_QUALIF INT NOT NULL,
ID_FUNCIO INT NOT NULL,
primary key (ID_QUALIF, ID_FUNCIO),
CONSTRAINT QUALIF_FUNCIO FOREIGN KEY (ID_QUALIF) REFERENCES QUALIFICAÇÕES (ID_QUALIFICAÇÃO),
CONSTRAINT FUNCIO_QUALIF FOREIGN KEY (ID_FUNCIO) REFERENCES FUNCIONARIOS (ID_FUNCIONARIO)
);

create TABLE IF NOT EXISTS LOCALIZACOES_PROJETOS_SOCIAIS(
ID_LOC INT NOT NULL,
ID_PROJ_SOC INT NOT NULL,
primary key (ID_LOC, ID_PROJ_SOC),
CONSTRAINT LOC_PROJ FOREIGN KEY (ID_LOC) REFERENCES LOCALIZAÇÕES (ID_LOCALIZAÇÃO),
constraint PROJ_LOC FOREIGN KEY (ID_PROJ_SOC) REFERENCES PROJETOS_SOCIAIS (ID_PROJETO_SOCIAL)
);

create TABLE IF NOT EXISTS INSTITUICOES_PROJETOS_SOCIAIS(
ID_INST INT NOT NULL,
ID_PROJ_SOC INT NOT NULL,
primary key (ID_INST, ID_PROJ_SOC),
CONSTRAINT INST_PROJ FOREIGN KEY (ID_INST) REFERENCES INSTITUICOES_CARENTES (ID_INSTITUICAO_CARENTE),
CONSTRAINT PROJ_INST FOREIGN KEY (ID_PROJ_SOC) REFERENCES PROJETOS_SOCIAIS (ID_PROJETO_SOCIAL)
);

CREATE TABLE IF NOT EXISTS EQUIPAMENTOS_PROJETOS_SOCIAIS(
ID_EQUIP INT NOT NULL,
ID_PROJ_SOC INT NOT NULL,
primary key (ID_EQUIP, ID_PROJ_SOC),
constraint EQUIP_PROJ_SOC FOREIGN KEY (ID_EQUIP) REFERENCES EQUIPAMENTOS (ID_EQUIPAMENTO),
CONSTRAINT PROJ_SOC_EQUIP FOREIGN KEY (ID_PROJ_SOC) REFERENCES PROJETOS_SOCIAIS (ID_PROJETO_SOCIAL)
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS_PROJETOS_SOCIAIS(
ID_PROJ_SOC INT NOT NULL,
ID_FUNCIO INT NOT NULL,
primary key (ID_PROJ_SOC, ID_FUNCIO),
constraint PROJ_SOC_FUNCIO foreign key (ID_PROJ_SOC) REFERENCES PROJETOS_SOCIAIS (ID_PROJETO_SOCIAL),
CONSTRAINT FUNCIO_PROJ_SOC FOREIGN KEY (ID_FUNCIO) REFERENCES FUNCIONARIOS (ID_FUNCIONARIO)
);

CREATE TABLE IF NOT EXISTS MATERIAIS_PROJETOS_SOCIAIS(
ID_PROJ_SOC INT NOT NULL,
ID_MAT INT NOT NULL,
primary key (ID_PROJ_SOC, ID_MAT),
constraint PROJ_SOC_MAT foreign key (ID_PROJ_SOC) REFERENCES PROJETOS_SOCIAIS (ID_PROJETO_SOCIAL),
CONSTRAINT MAT_PROJ_SOC FOREIGN KEY (ID_MAT) REFERENCES MATERIAIS (ID_MATERIAL)
);
